### ISSUE TITLE
Two pieces of feedback!

### ISSUE THREAD

**Issue by Bananaman** [99dsimonp/PixelBot#1]
Hi man, nice work! Got some quick feedback!

1. I recommend that you switch your projects from `mss` to `d3dshot` (with Numpy set as the engine via the API constructor) for screenshots. This leads to 12x speedup of screen capture!
2. Blizzard recently decided to forbid multi boxing which in turn means they watch for input broadcasting/fake input now. And they are bale to detect that input was made by fake programs. I worry a bit. What month did you begin bottling via Python and how long have you been doing it? No bans? :-)

**Comment by 99dsimonp** [comment]
Thanks for the input. I wrote the bot for a private server I was playing on, so this has never seen any action in retail. I do not suggest using it there.

**Comment by Bananaman** [comment]
Ahh gotcha. Thanks for the warning. I won't!
